using System.Text.Json;
using System.Xml.Linq;
using AiRepoKit.Cli.Models;
using AiRepoKit.Cli.Services;
using AiRepoKit.Cli.Services.DotNetSdk;

namespace AiRepoKit.Cli.Services.SdkAlignment;

public sealed class SdkAlignmentService : ISdkAlignmentService
{
    private const string ExpectedTargetFramework = "net10.0";

    private static readonly HashSet<string> IgnoredDirectories = new(
        [
            "bin",
            "obj",
            ".git",
            ".vs",
            ".vscode",
            ".idea",
            "Logs",
            "AutoGenerated",
            "oracle-data",
            "wwwroot",
            "artifacts",
            ".tmp",
            "node_modules"
        ],
        StringComparer.OrdinalIgnoreCase);

    private readonly IProcessRunner _processRunner;

    public SdkAlignmentService()
        : this(new DotNetSdkProcessRunner())
    {
    }

    public SdkAlignmentService(IProcessRunner processRunner)
    {
        _processRunner = processRunner ?? throw new ArgumentNullException(nameof(processRunner));
    }

    public SdkAlignmentRunResult Run(string repoRoot)
    {
        if (string.IsNullOrWhiteSpace(repoRoot))
        {
            return SdkAlignmentRunResult.Failure(
                "Repository root path cannot be empty.");
        }

        string root = Path.GetFullPath(repoRoot);

        ProcessResult version = _processRunner.Run(
            "dotnet",
            ["--version"],
            root);

        if (!version.Success)
        {
            return SdkAlignmentRunResult.Failure(
                FormatProcessFailure("dotnet --version", version));
        }

        ProcessResult sdks = _processRunner.Run(
            "dotnet",
            ["--list-sdks"],
            root);

        if (!sdks.Success)
        {
            return SdkAlignmentRunResult.Failure(
                FormatProcessFailure("dotnet --list-sdks", sdks));
        }

        try
        {
            List<SdkAlignmentProject> projects = Directory
                .EnumerateFiles(
                    root,
                    "*.csproj",
                    SearchOption.AllDirectories)
                .Select(path => new
                {
                    FullPath = path,
                    RelativePath = GetRelativePath(root, path)
                })
                .Where(item => !ShouldIgnorePath(item.RelativePath))
                .OrderBy(
                    item => item.RelativePath,
                    StringComparer.Ordinal)
                .Select(item => new SdkAlignmentProject
                {
                    Project = item.RelativePath,
                    TargetFrameworks = ReadTargetFrameworks(
                        item.FullPath)
                })
                .ToList();

            SdkAlignmentReport report = new()
            {
                ExpectedTargetFramework = ExpectedTargetFramework,
                DotNetSdkVersion = version.StandardOutput.Trim(),
                DotNetSdks = SplitLines(sdks.StandardOutput),
                Projects = projects
            };

            string reportsRoot = Path.Combine(
                root,
                ".ai",
                "generated",
                "reports");

            Directory.CreateDirectory(reportsRoot);

            string reportPath = Path.Combine(
                reportsRoot,
                "sdk-alignment-report.json");

            string json = JsonSerializer.Serialize(
                report,
                new JsonSerializerOptions
                {
                    WriteIndented = true
                });

            File.WriteAllText(reportPath, json);

            return SdkAlignmentRunResult.Success(report);
        }
        catch (Exception exception)
        {
            return SdkAlignmentRunResult.Failure(
                $"SDK alignment failed: {exception.Message}");
        }
    }

    private static IReadOnlyList<string> SplitLines(string value)
    {
        return value
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace('\r', '\n')
            .Split(
                '\n',
                StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .ToArray();
    }

    private static string ReadTargetFrameworks(
        string projectPath)
    {
        XDocument document = XDocument.Load(projectPath);

        IEnumerable<string> singleFrameworks = document
            .Descendants()
            .Where(element =>
                element.Name.LocalName == "TargetFramework")
            .Select(element => element.Value);

        IEnumerable<string> multipleFrameworks = document
            .Descendants()
            .Where(element =>
                element.Name.LocalName == "TargetFrameworks")
            .SelectMany(element =>
                element.Value.Split(
                    ';',
                    StringSplitOptions.RemoveEmptyEntries));

        return string.Join(
            ";",
            singleFrameworks
                .Concat(multipleFrameworks)
                .Select(value => value.Trim())
                .Where(value => value.Length > 0)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(
                    value => value,
                    StringComparer.Ordinal));
    }

    private static bool ShouldIgnorePath(
        string relativePath)
    {
        string[] segments = relativePath.Split(
            '/',
            StringSplitOptions.RemoveEmptyEntries);

        if (segments.Any(segment =>
                IgnoredDirectories.Contains(segment)))
        {
            return true;
        }

        return segments.Length > 0 &&
            segments[0].StartsWith(
                ".build-",
                StringComparison.OrdinalIgnoreCase);
    }

    private static string GetRelativePath(
        string root,
        string fullPath)
    {
        return Path
            .GetRelativePath(root, fullPath)
            .Replace('\\', '/');
    }

    private static string FormatProcessFailure(
        string operation,
        ProcessResult process)
    {
        string detail = string.IsNullOrWhiteSpace(
            process.StandardError)
            ? $"exit {process.ExitCode}"
            : process.StandardError.Trim();

        return $"{operation} failed: {detail}";
    }
}
