using System.Text;
using System.Text.Json;
using AiRepoKit.Cli.Services.SecretScan;
using Xunit;

namespace AiRepoKit.Cli.Tests;

public sealed class SecretScanServiceTests
{
    [Fact]
    public void Run_EmptyRepositoryWritesSafeReport()
    {
        using TempRepo repo =
            new();

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.False(
            result.Report!.SecretsExposed);

        Assert.False(
            result.Report.SecretValuesReturned);

        Assert.True(
            result.Report.RedactedOnly);

        Assert.Equal(
            0,
            result.Report.FindingCount);

        Assert.Empty(
            result.Report.Findings);

        Assert.True(
            File.Exists(
                repo.ReportPath));
    }

    [Fact]
    public void Run_DetectsAllLegacyPatternFamiliesCaseInsensitively()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "patterns.txt",
            """
            PASSWORD = one
            PaSsWd: two
            PWD=three
            SeCrEt:four
            TOKEN=five
            API_KEY=six
            api-key:seven
            ConnectionString = eight
            """);

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            8,
            result.Report!.FindingCount);

        Assert.Equal(
            8,
            result.Report.Findings.Count);
    }

    [Fact]
    public void Run_DetectsPatternWithoutSecretValue()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "empty-value.txt",
            "password =");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            1,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_AddsAtMostOneFindingPerLine()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "single-line.txt",
            "password=one token=two api_key=three");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            1,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_CountsMultipleMatchingLines()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "multi-line.txt",
            """
            password=one
            safe line
            token=two
            secret=three
            """);

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            3,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_NeverEmitsMatchedSecretValues()
    {
        using TempRepo repo =
            new();

        const string secretValue =
            "ULTRA_SECRET_VALUE_123456789";

        repo.WriteText(
            "safe-to-scan.txt",
            "token=" + secretValue);

        SecretScanRunResult result =
            RunSuccess(repo);

        string json =
            File.ReadAllText(
                repo.ReportPath);

        Assert.DoesNotContain(
            secretValue,
            json,
            StringComparison.Ordinal);

        SecretScanFinding finding =
            Assert.Single(
                result.Report!.Findings);

        Assert.Equal(
            "SecretPattern",
            finding.Category);

        Assert.Equal(
            "High",
            finding.Severity);

        Assert.Equal(
            "<redacted>",
            finding.Preview);

        Assert.DoesNotContain(
            secretValue,
            finding.File,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Run_CapsFindingsAtOneHundredButPreservesTotalCount()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "many.txt",
            string.Join(
                Environment.NewLine,
                Enumerable
                    .Range(
                        0,
                        105)
                    .Select(
                        index =>
                            $"token=value-{index}")));

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            105,
            result.Report!.FindingCount);

        Assert.Equal(
            100,
            result.Report.Findings.Count);
    }

    [Fact]
    public void Run_IgnoresConfiguredDirectorySegments()
    {
        using TempRepo repo =
            new();

        string[] ignored =
        [
            "bin",
            "obj",
            ".git",
            ".vs",
            ".vscode",
            ".idea",
            "Logs",
            "AutoGenerated",
            "oracle-data",
            "wwwroot",
            "artifacts",
            ".tmp",
            "node_modules"
        ];

        foreach (string directory in
            ignored)
        {
            repo.WriteText(
                $"{directory}/secret.txt",
                "token=do-not-scan");
        }

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            0,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_IgnoresTopLevelBuildDirectory()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            ".build-cache/secret.txt",
            "token=do-not-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            0,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_IgnoresTopLevelBuildPrefixedFile()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            ".build-generated.txt",
            "token=do-not-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            0,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_DoesNotIgnoreNestedBuildDirectory()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "src/.build-cache/scan.txt",
            "token=must-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        SecretScanFinding finding =
            Assert.Single(
                result.Report!.Findings);

        Assert.Equal(
            "src/.build-cache/scan.txt",
            finding.File);
    }

    [Fact]
    public void Run_IgnoresMigrationsSegments()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "src/Migrations/001.sql",
            "token=do-not-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            0,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_IgnoresBlockedFileNames()
    {
        using TempRepo repo =
            new();

        string[] blocked =
        [
            "APPSETTINGS.Production.JSON",
            "docker-compose.override.YML",
            "docker-compose.local.YAML",
            "private.KEY",
            "certificate.PEM",
            "certificate.PFX",
            "store.JKS",
            "store.KEYSTORE"
        ];

        foreach (string file in
            blocked)
        {
            repo.WriteText(
                file,
                "token=do-not-scan");
        }

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            0,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_ScansFilesRegardlessOfExtension()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "data.custombinary",
            "token=must-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            1,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_ExcludesFilesAtOneMiBOrLarger()
    {
        using TempRepo repo =
            new();

        repo.WriteSizedAsciiFile(
            "exact-limit.txt",
            1048576,
            "token=do-not-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            1048576,
            new FileInfo(
                repo.GetPath(
                    "exact-limit.txt"))
                .Length);

        Assert.Equal(
            0,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_IncludesFilesBelowOneMiB()
    {
        using TempRepo repo =
            new();

        repo.WriteSizedAsciiFile(
            "below-limit.txt",
            1048575,
            "token=must-scan");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            1048575,
            new FileInfo(
                repo.GetPath(
                    "below-limit.txt"))
                .Length);

        Assert.Equal(
            1,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_NormalizesAndSortsRelativePathsDeterministically()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "z/Z.txt",
            "token=z");

        repo.WriteText(
            "a/A.txt",
            "token=a");

        SecretScanRunResult result =
            RunSuccess(repo);

        Assert.Equal(
            [
                "a/A.txt",
                "z/Z.txt"
            ],
            result.Report!
                .Findings
                .Select(
                    finding =>
                        finding.File));

        Assert.All(
            result.Report.Findings,
            finding =>
                Assert.DoesNotContain(
                    '\\',
                    finding.File));
    }

    [Fact]
    public void Run_WritesExpectedJsonContract()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "scan.txt",
            "token=value");

        RunSuccess(repo);

        using JsonDocument document =
            JsonDocument.Parse(
                File.ReadAllText(
                    repo.ReportPath));

        JsonElement root =
            document.RootElement;

        Assert.False(
            root.GetProperty(
                "SecretsExposed")
                .GetBoolean());

        Assert.False(
            root.GetProperty(
                "SecretValuesReturned")
                .GetBoolean());

        Assert.True(
            root.GetProperty(
                "RedactedOnly")
                .GetBoolean());

        Assert.Equal(
            1,
            root.GetProperty(
                "FindingCount")
                .GetInt32());

        JsonElement finding =
            root.GetProperty(
                "Findings")[0];

        Assert.Equal(
            "scan.txt",
            finding.GetProperty(
                "file")
                .GetString());

        Assert.Equal(
            "SecretPattern",
            finding.GetProperty(
                "category")
                .GetString());

        Assert.Equal(
            "High",
            finding.GetProperty(
                "severity")
                .GetString());

        Assert.Equal(
            "<redacted>",
            finding.GetProperty(
                "preview")
                .GetString());

        Assert.False(
            finding.TryGetProperty(
                "File",
                out _));
    }

    [Fact]
    public void Run_FindingsDoNotMakeRunFail()
    {
        using TempRepo repo =
            new();

        repo.WriteText(
            "finding.txt",
            "password=detected");

        SecretScanRunResult result =
            new SecretScanService()
                .Run(
                    repo.Root);

        Assert.True(
            result.IsSuccess,
            result.ErrorMessage);

        Assert.Equal(
            1,
            result.Report!.FindingCount);
    }

    [Fact]
    public void Run_InvalidRepositoryPathReturnsUnprefixedFailureDetail()
    {
        SecretScanRunResult result =
            new SecretScanService()
                .Run(
                    "\0");

        Assert.False(
            result.IsSuccess);

        Assert.Null(
            result.Report);

        Assert.False(
            string.IsNullOrWhiteSpace(
                result.ErrorMessage));

        Assert.False(
            result.ErrorMessage!.StartsWith(
                "Secret scan failed:",
                StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public void Run_MissingRepositoryReturnsFailureAndDoesNotWriteReport()
    {
        string missing =
            Path.Combine(
                Path.GetTempPath(),
                "airepo_secret_scan_missing_" +
                Guid.NewGuid()
                    .ToString("N"));

        SecretScanRunResult result =
            new SecretScanService()
                .Run(
                    missing);

        Assert.False(
            result.IsSuccess);

        Assert.Null(
            result.Report);

        Assert.Equal(
            "Repository root path was not found.",
            result.ErrorMessage);

        Assert.False(
            Directory.Exists(
                missing));
    }

    private static SecretScanRunResult RunSuccess(
        TempRepo repo)
    {
        SecretScanRunResult result =
            new SecretScanService()
                .Run(
                    repo.Root);

        Assert.True(
            result.IsSuccess,
            result.ErrorMessage);

        Assert.NotNull(
            result.Report);

        return result;
    }

    private sealed class TempRepo :
        IDisposable
    {
        public TempRepo()
        {
            Root =
                Path.Combine(
                    Path.GetTempPath(),
                    "airepo_secret_scan_" +
                    Guid.NewGuid()
                        .ToString("N"));

            Directory.CreateDirectory(
                Root);
        }

        public string Root { get; }

        public string ReportPath =>
            GetPath(
                SecretScanService.ReportRelativePath);

        public string GetPath(
            string relativePath)
        {
            return Path.Combine(
                Root,
                relativePath.Replace(
                    '/',
                    Path.DirectorySeparatorChar));
        }

        public void WriteText(
            string relativePath,
            string content)
        {
            string path =
                GetPath(
                    relativePath);

            string? directory =
                Path.GetDirectoryName(
                    path);

            if (!string.IsNullOrWhiteSpace(
                    directory))
            {
                Directory.CreateDirectory(
                    directory);
            }

            File.WriteAllText(
                path,
                content,
                new UTF8Encoding(
                    encoderShouldEmitUTF8Identifier: false));
        }

        public void WriteSizedAsciiFile(
            string relativePath,
            int byteCount,
            string prefix)
        {
            if (prefix.Length > byteCount)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(byteCount));
            }

            WriteText(
                relativePath,
                prefix +
                new string(
                    'x',
                    byteCount -
                    prefix.Length));
        }

        public void Dispose()
        {
            if (!Directory.Exists(
                    Root))
            {
                return;
            }

            try
            {
                Directory.Delete(
                    Root,
                    recursive: true);
            }
            catch
            {
            }
        }
    }
}
