namespace AiRepoKit.Cli.Services.CodeIndex;

public sealed record CodeFileDiscoveryResult(
    IReadOnlyList<string> Files,
    IReadOnlyList<string> IgnoredDirectories,
    IReadOnlyList<string> IgnoredFiles,
    bool Truncated);

public sealed class CodeFileDiscoveryService
{
    private static readonly string[] DirectoryIgnoreEntries =
    [
        ".git",
        "bin",
        "obj",
        ".vs",
        ".vscode",
        ".idea",
        "node_modules",
        "dist",
        "build",
        "artifacts",
        ".tmp",
        "Logs",
        "AutoGenerated",
        "oracle-data",
        "wwwroot/uploads",
        "Tools/AISandbox",
        "Migrations"
    ];

    private static readonly string[] FileIgnoreEntries =
    [
        "*.Designer.cs",
        "*.g.cs",
        "*.AssemblyInfo.cs",
        "appsettings*.json",
        "key.json",
        "*.pem",
        "*.pfx",
        "*.key",
        "*.jks",
        "*.keystore"
    ];

    public CodeFileDiscoveryResult Discover(string repoRoot_, int maxFiles_)
    {
        string repoRoot = Path.GetFullPath(repoRoot_);
        List<string> files = [];
        Stack<string> pending = new();
        pending.Push(repoRoot);
        bool truncated = false;

        while (pending.Count > 0)
        {
            string current = pending.Pop();

            foreach (string file in Directory.EnumerateFiles(current, "*.cs", SearchOption.TopDirectoryOnly).Order(StringComparer.OrdinalIgnoreCase))
            {
                string relativePath = Path.GetRelativePath(repoRoot, file).Replace('\\', '/');
                if (this.IsIgnoredFile(relativePath))
                {
                    continue;
                }

                files.Add(relativePath);
                if (files.Count >= maxFiles_)
                {
                    truncated = true;
                    return new CodeFileDiscoveryResult(files, DirectoryIgnoreEntries, FileIgnoreEntries, truncated);
                }
            }

            foreach (string directory in Directory.EnumerateDirectories(current, "*", SearchOption.TopDirectoryOnly).OrderDescending())
            {
                string relativePath = Path.GetRelativePath(repoRoot, directory).Replace('\\', '/');
                if (!this.IsIgnoredDirectory(relativePath))
                {
                    pending.Push(directory);
                }
            }
        }

        return new CodeFileDiscoveryResult(files, DirectoryIgnoreEntries, FileIgnoreEntries, truncated);
    }

    public bool IsIgnoredDirectory(string relativePath_)
    {
        string normalized = relativePath_.Replace('\\', '/').Trim('/');
        string name = Path.GetFileName(normalized);
        return DirectoryIgnoreEntries.Any(entry_ =>
            normalized.Equals(entry_, StringComparison.OrdinalIgnoreCase)
            || normalized.StartsWith(entry_ + "/", StringComparison.OrdinalIgnoreCase)
            || normalized.EndsWith("/" + entry_, StringComparison.OrdinalIgnoreCase)
            || name.Equals(entry_, StringComparison.OrdinalIgnoreCase));
    }

    public bool IsIgnoredFile(string relativePath_)
    {
        string normalized = relativePath_.Replace('\\', '/').TrimStart('/');
        string fileName = Path.GetFileName(normalized);
        if (normalized.Contains("/docker-compose", StringComparison.OrdinalIgnoreCase)
            || fileName.StartsWith("docker-compose", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return FileIgnoreEntries.Any(pattern_ => MatchesPattern(fileName, pattern_));
    }

    private static bool MatchesPattern(string fileName_, string pattern_)
    {
        if (!pattern_.Contains('*', StringComparison.Ordinal))
        {
            return fileName_.Equals(pattern_, StringComparison.OrdinalIgnoreCase);
        }

        string[] parts = pattern_.Split('*', StringSplitOptions.None);
        if (parts.Length == 2)
        {
            return fileName_.StartsWith(parts[0], StringComparison.OrdinalIgnoreCase)
                && fileName_.EndsWith(parts[1], StringComparison.OrdinalIgnoreCase);
        }

        return false;
    }
}
