using System.Globalization;
using System.Text.Json;
using System.Xml.Linq;
using AiRepoKit.Cli.Models;
using AiRepoKit.Cli.Services;
using AiRepoKit.Cli.Services.DotNetSdk;

namespace AiRepoKit.Cli.Services.AiContextUpdate;

public sealed class AiContextUpdateService :
    IAiContextUpdateService
{
    private static readonly JsonSerializerOptions JsonOptions =
        new()
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

    private static readonly HashSet<string> IgnoredDirectories =
        new(
            [
                "bin",
                "obj",
                ".git",
                ".vs",
                ".vscode",
                ".idea",
                "Logs",
                "AutoGenerated",
                "oracle-data",
                "wwwroot",
                "artifacts",
                ".tmp",
                "node_modules"
            ],
            StringComparer.OrdinalIgnoreCase);

    private static readonly string[] AllowedContextFilePaths =
    [
        ".ai/README.md",
        ".ai/ai-operating-rules.md",
        ".ai/automation-risks.md",
        ".ai/build-profile.md",
        ".ai/codex-usage-guide.md",
        ".ai/project-map.md",
        ".ai/sdk-profile.md",
        ".ai/test-profile.md",
        ".ai/tool-roadmap.md",
        ".ai/context-budget.json",
        ".ai/generated/inventories/project-inventory.json",
        ".ai/generated/inventories/project-references.json",
        ".ai/generated/inventories/package-inventory.json",
        ".ai/generated/inventories/sdk-inventory.json",
        ".ai/generated/inventories/symbol-inventory.json",
        ".ai/generated/inventories/symbol-inventory.md",
        ".ai/generated/inventories/endpoint-inventory.json",
        ".ai/generated/inventories/endpoint-inventory.md",
        ".ai/generated/reports/mcp-budget-report.json",
        ".ai/generated/reports/mcp-budget-report.md",
        ".ai/generated/reports/sdk-alignment-report.json",
        ".ai/generated/reports/secret-scan-report.json",
        ".ai/generated/reports/build-diagnostics-report.json",
        ".ai/generated/reports/latest-build-summary.json",
        ".ai/generated/summaries/generated-context-summary.md",
        ".ai/manifests/mcp-context-manifest.md",
        ".ai/playbooks/change-ui.md",
        ".ai/playbooks/diagnose-build.md",
        ".ai/playbooks/update-package.md",
        ".ai/playbooks/inspect-security.md"
    ];

    private static readonly string[] RestrictedPathPatterns =
    [
        ".git",
        ".vs",
        ".vscode",
        ".idea",
        "bin",
        "obj",
        "artifacts",
        ".tmp",
        ".dotnet-home",
        ".codex/config.toml",
        "Logs",
        "AutoGenerated",
        "oracle-data",
        "wwwroot",
        ".build-*",
        "appsettings*.json",
        "docker-compose*.yml",
        "docker-compose*.yaml",
        "*.key",
        "*.pem",
        "*.pfx",
        "*.jks",
        "*.keystore",
        "migrations"
    ];

    private readonly IProcessRunner _processRunner;
    private readonly TimeProvider _timeProvider;

    public AiContextUpdateService()
        : this(
            new DotNetSdkProcessRunner(),
            TimeProvider.System)
    {
    }

    public AiContextUpdateService(
        IProcessRunner processRunner)
        : this(
            processRunner,
            TimeProvider.System)
    {
    }

    public AiContextUpdateService(
        IProcessRunner processRunner,
        TimeProvider timeProvider)
    {
        _processRunner =
            processRunner ??
            throw new ArgumentNullException(
                nameof(processRunner));

        _timeProvider =
            timeProvider ??
            throw new ArgumentNullException(
                nameof(timeProvider));
    }

    public AiContextUpdateRunResult Run(
        string repoRoot,
        AiContextUpdateOptions? options = null)
    {
        if (string.IsNullOrWhiteSpace(repoRoot))
        {
            return AiContextUpdateRunResult.Failure(
                "Repository root path cannot be empty.");
        }

        string root = Path.GetFullPath(repoRoot);

        if (!Directory.Exists(root))
        {
            return AiContextUpdateRunResult.Failure(
                "Repository root path does not exist.");
        }

        AiContextUpdateOptions effectiveOptions =
            options ?? new AiContextUpdateOptions();

        try
        {
            string mainSolution =
                FindMainSolution(root);

            List<ParsedProject> projects =
                ReadProjects(root);

            ProcessResult versionResult =
                _processRunner.Run(
                    "dotnet",
                    ["--version"],
                    root);

            ProcessResult sdkListResult =
                _processRunner.Run(
                    "dotnet",
                    ["--list-sdks"],
                    root);

            string sdkVersion =
                versionResult.Success
                    ? versionResult.StandardOutput.Trim()
                    : "Unavailable";

            IReadOnlyList<string> sdkList =
                sdkListResult.Success
                    ? SplitLines(
                        sdkListResult.StandardOutput)
                    : ["Unavailable"];

            string generatedAtLocal =
                _timeProvider
                    .GetLocalNow()
                    .ToString(
                        "yyyy-MM-dd HH:mm:ss zzz",
                        CultureInfo.InvariantCulture);

            ManifestModel manifest =
                BuildManifest(
                    root,
                    mainSolution,
                    generatedAtLocal,
                    projects.Count,
                    effectiveOptions);

            ProjectInventoryModel projectInventory =
                new()
                {
                    GeneratedAtLocal = generatedAtLocal,
                    Projects = projects
                        .Select(project =>
                            new ProjectInventoryEntry
                            {
                                Path = project.Path,
                                TargetFrameworks =
                                    project.TargetFrameworks
                            })
                        .ToArray()
                };

            ProjectReferencesModel projectReferences =
                new()
                {
                    GeneratedAtLocal = generatedAtLocal,
                    References = projects
                        .SelectMany(project =>
                            project.References)
                        .ToArray()
                };

            PackageInventoryModel packageInventory =
                new()
                {
                    GeneratedAtLocal = generatedAtLocal,
                    Packages = projects
                        .SelectMany(project =>
                            project.Packages)
                        .ToArray()
                };

            SdkInventoryModel sdkInventory =
                new()
                {
                    GeneratedAtLocal = generatedAtLocal,
                    DotNetSdkVersion = sdkVersion,
                    DotNetSdks = sdkList,
                    ExpectedTargetFramework =
                        effectiveOptions.TargetFramework
                };

            string manifestRoot =
                Path.Combine(
                    root,
                    ".ai",
                    "manifests");

            string inventoriesRoot =
                Path.Combine(
                    root,
                    ".ai",
                    "generated",
                    "inventories");

            string summariesRoot =
                Path.Combine(
                    root,
                    ".ai",
                    "generated",
                    "summaries");

            Directory.CreateDirectory(manifestRoot);
            Directory.CreateDirectory(inventoriesRoot);
            Directory.CreateDirectory(summariesRoot);

            WriteJson(
                Path.Combine(
                    manifestRoot,
                    "mcp-context-manifest.json"),
                manifest);

            WriteJson(
                Path.Combine(
                    inventoriesRoot,
                    "project-inventory.json"),
                projectInventory);

            WriteJson(
                Path.Combine(
                    inventoriesRoot,
                    "project-references.json"),
                projectReferences);

            WriteJson(
                Path.Combine(
                    inventoriesRoot,
                    "package-inventory.json"),
                packageInventory);

            WriteJson(
                Path.Combine(
                    inventoriesRoot,
                    "sdk-inventory.json"),
                sdkInventory);

            string summaryMarkdown =
                BuildSummaryMarkdown(
                    generatedAtLocal,
                    mainSolution,
                    projects.Count,
                    packageInventory.Packages.Count,
                    projectReferences.References.Count);

            File.WriteAllText(
                Path.Combine(
                    summariesRoot,
                    "generated-context-summary.md"),
                summaryMarkdown);

            return AiContextUpdateRunResult.Success();
        }
        catch (Exception exception)
        {
            return AiContextUpdateRunResult.Failure(
                ProcessRunner.Redact(
                    $"AI context update failed: {exception.Message}"));
        }
    }

    private static string FindMainSolution(
        string root)
    {
        return Directory
            .EnumerateFiles(
                root,
                "*",
                SearchOption.TopDirectoryOnly)
            .Where(path =>
                Path.GetExtension(path).Equals(
                    ".sln",
                    StringComparison.OrdinalIgnoreCase))
            .Select(Path.GetFileName)
            .Where(name =>
                !string.IsNullOrEmpty(name))
            .OrderBy(
                name => name,
                StringComparer.Ordinal)
            .FirstOrDefault() ??
            string.Empty;
    }

    private static List<ParsedProject> ReadProjects(
        string root)
    {
        return Directory
            .EnumerateFiles(
                root,
                "*",
                SearchOption.AllDirectories)
            .Where(path =>
                Path.GetExtension(path).Equals(
                    ".csproj",
                    StringComparison.OrdinalIgnoreCase))
            .Select(path => new
            {
                FullPath = path,
                RelativePath =
                    GetRelativePath(
                        root,
                        path)
            })
            .Where(item =>
                !ShouldIgnorePath(
                    item.RelativePath))
            .OrderBy(
                item => item.RelativePath,
                StringComparer.Ordinal)
            .Select(item =>
                ReadProject(
                    item.FullPath,
                    item.RelativePath))
            .ToList();
    }

    private static ParsedProject ReadProject(
        string fullPath,
        string relativePath)
    {
        XDocument document =
            XDocument.Load(fullPath);

        IReadOnlyList<string> targetFrameworks =
            document
                .Descendants()
                .Where(element =>
                    element.Name.LocalName is
                        "TargetFramework" or
                        "TargetFrameworks")
                .SelectMany(element =>
                    element.Name.LocalName ==
                    "TargetFrameworks"
                        ? element.Value.Split(
                            ';',
                            StringSplitOptions.RemoveEmptyEntries)
                        : [element.Value])
                .Select(value => value.Trim())
                .Where(value => value.Length > 0)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(
                    value => value,
                    StringComparer.Ordinal)
                .ToArray();

        IReadOnlyList<ProjectReferenceEntry> references =
            document
                .Descendants()
                .Where(element =>
                    element.Name.LocalName ==
                    "ProjectReference")
                .Select(element =>
                    GetMetadataValue(
                        element,
                        "Include"))
                .Where(include =>
                    !string.IsNullOrEmpty(include))
                .Select(include =>
                    new ProjectReferenceEntry
                    {
                        Project = relativePath,
                        Reference = include!
                            .Replace(
                                '\\',
                                '/')
                    })
                .ToArray();

        IReadOnlyList<PackageInventoryEntry> packages =
            document
                .Descendants()
                .Where(element =>
                    element.Name.LocalName ==
                    "PackageReference")
                .Select(element => new
                {
                    Include =
                        GetMetadataValue(
                            element,
                            "Include"),
                    Version =
                        GetMetadataValue(
                            element,
                            "Version")
                })
                .Where(item =>
                    !string.IsNullOrEmpty(
                        item.Include))
                .Select(item =>
                    new PackageInventoryEntry
                    {
                        Project = relativePath,
                        Package = item.Include!,
                        Version =
                            item.Version ??
                            string.Empty
                    })
                .ToArray();

        return new ParsedProject(
            relativePath,
            targetFrameworks,
            references,
            packages);
    }

    private static string? GetMetadataValue(
        XElement element,
        string name)
    {
        XAttribute? attribute =
            element
                .Attributes()
                .FirstOrDefault(attribute =>
                    attribute.Name.LocalName.Equals(
                        name,
                        StringComparison.OrdinalIgnoreCase));

        if (attribute is not null)
        {
            return attribute.Value;
        }

        XElement? child =
            element
                .Elements()
                .FirstOrDefault(child =>
                    child.Name.LocalName.Equals(
                        name,
                        StringComparison.OrdinalIgnoreCase));

        return child?.Value;
    }

    private static bool ShouldIgnorePath(
        string relativePath)
    {
        string[] segments =
            relativePath.Split(
                '/',
                StringSplitOptions.RemoveEmptyEntries);

        if (segments.Any(segment =>
                IgnoredDirectories.Contains(segment)))
        {
            return true;
        }

        return segments.Length > 0 &&
            segments[0].StartsWith(
                ".build-",
                StringComparison.OrdinalIgnoreCase);
    }

    private static string GetRelativePath(
        string root,
        string fullPath)
    {
        return Path
            .GetRelativePath(
                root,
                fullPath)
            .Replace(
                '\\',
                '/');
    }

    private static IReadOnlyList<string> SplitLines(
        string value)
    {
        return value
            .Replace(
                "\r\n",
                "\n",
                StringComparison.Ordinal)
            .Replace(
                '\r',
                '\n')
            .Split(
                '\n',
                StringSplitOptions.RemoveEmptyEntries)
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .ToArray();
    }

    private static ManifestModel BuildManifest(
        string root,
        string mainSolution,
        string generatedAtLocal,
        int projectCount,
        AiContextUpdateOptions options)
    {
        return new ManifestModel
        {
            RepoName =
                new DirectoryInfo(root).Name,
            MainSolution = mainSolution,
            GeneratedAtLocal = generatedAtLocal,
            TargetFramework =
                options.TargetFramework,
            McpServerName =
                options.McpServerName,
            McpProjectRelativePath =
                options.McpProjectRelativePath,
            ProjectCount = projectCount,
            AllowedContextFiles =
                AllowedContextFilePaths,
            RestrictedPaths =
                RestrictedPathPatterns,
            Budgets =
                new BudgetModel
                {
                    CompactBytes = 8192,
                    FullBytes = 49152,
                    CombinedBytes = 65536,
                    FileReadBytes = 1048576,
                    SearchDefaultLimit = 5,
                    SearchHardLimit = 25,
                    ArrayDefaultLimit = 25,
                    ArrayHardLimit = 100,
                    PreviewChars = 240
                }
        };
    }

    private static string BuildSummaryMarkdown(
        string generatedAtLocal,
        string mainSolution,
        int projectCount,
        int packageCount,
        int referenceCount)
    {
        string[] lines =
        [
            "# Generated Context Summary",
            "",
            $"- Generated: {generatedAtLocal}",
            $"- Main solution: {mainSolution}",
            $"- Projects: {projectCount}",
            $"- Packages: {packageCount}",
            $"- Project references: {referenceCount}"
        ];

        return string.Join(
            Environment.NewLine,
            lines) +
            Environment.NewLine;
    }

    private static void WriteJson<T>(
        string path,
        T value)
    {
        string json =
            JsonSerializer.Serialize(
                value,
                JsonOptions);

        File.WriteAllText(
            path,
            json);
    }

    private sealed record ParsedProject(
        string Path,
        IReadOnlyList<string> TargetFrameworks,
        IReadOnlyList<ProjectReferenceEntry> References,
        IReadOnlyList<PackageInventoryEntry> Packages);

    private sealed class ManifestModel
    {
        public string RepoName { get; init; } =
            string.Empty;

        public string MainSolution { get; init; } =
            string.Empty;

        public string GeneratedAtLocal { get; init; } =
            string.Empty;

        public string TargetFramework { get; init; } =
            string.Empty;

        public string McpServerName { get; init; } =
            string.Empty;

        public string McpProjectRelativePath { get; init; } =
            string.Empty;

        public int ProjectCount { get; init; }

        public IReadOnlyList<string> AllowedContextFiles
        {
            get;
            init;
        } = [];

        public IReadOnlyList<string> RestrictedPaths
        {
            get;
            init;
        } = [];

        public BudgetModel Budgets { get; init; } =
            new();
    }

    private sealed class BudgetModel
    {
        public int CompactBytes { get; init; }

        public int FullBytes { get; init; }

        public int CombinedBytes { get; init; }

        public int FileReadBytes { get; init; }

        public int SearchDefaultLimit { get; init; }

        public int SearchHardLimit { get; init; }

        public int ArrayDefaultLimit { get; init; }

        public int ArrayHardLimit { get; init; }

        public int PreviewChars { get; init; }
    }

    private sealed class ProjectInventoryModel
    {
        public string GeneratedAtLocal { get; init; } =
            string.Empty;

        public IReadOnlyList<ProjectInventoryEntry> Projects
        {
            get;
            init;
        } = [];
    }

    private sealed class ProjectInventoryEntry
    {
        public string Path { get; init; } =
            string.Empty;

        public IReadOnlyList<string> TargetFrameworks
        {
            get;
            init;
        } = [];
    }

    private sealed class ProjectReferencesModel
    {
        public string GeneratedAtLocal { get; init; } =
            string.Empty;

        public IReadOnlyList<ProjectReferenceEntry> References
        {
            get;
            init;
        } = [];
    }

    private sealed class ProjectReferenceEntry
    {
        public string Project { get; init; } =
            string.Empty;

        public string Reference { get; init; } =
            string.Empty;
    }

    private sealed class PackageInventoryModel
    {
        public string GeneratedAtLocal { get; init; } =
            string.Empty;

        public IReadOnlyList<PackageInventoryEntry> Packages
        {
            get;
            init;
        } = [];
    }

    private sealed class PackageInventoryEntry
    {
        public string Project { get; init; } =
            string.Empty;

        public string Package { get; init; } =
            string.Empty;

        public string Version { get; init; } =
            string.Empty;
    }

    private sealed class SdkInventoryModel
    {
        public string GeneratedAtLocal { get; init; } =
            string.Empty;

        public string DotNetSdkVersion { get; init; } =
            string.Empty;

        public IReadOnlyList<string> DotNetSdks
        {
            get;
            init;
        } = [];

        public string ExpectedTargetFramework { get; init; } =
            string.Empty;
    }
}
