# Project Map

## Repository

- Name: `{{RepoName}}`
- Root: `<target-repo>`
- Main solution: `{{MainSolution}}`

## Common Areas

- Source projects: repository-specific.
- Tests: repository-specific.
- Tooling: `Tools/`
- AI context: `.ai/`

## Ignored Areas

`bin`, `obj`, `.git`, `.vs`, `.vscode`, `.idea`, `Logs`, `AutoGenerated`, `oracle-data`, `wwwroot`, and `.build-*`.
