using System.Text.Json;
using System.Text.RegularExpressions;
using AiRepoKit.Cli.Services;

namespace AiRepoKit.Cli.Services.SecretScan;

public sealed class SecretScanService :
    ISecretScanService
{
    public const string ReportRelativePath =
        ".ai/generated/reports/secret-scan-report.json";

    private const long MaxFileBytes =
        1048576;

    private const int MaxReportedFindings =
        100;

    private static readonly string[] IgnoredDirectories =
    [
        "bin",
        "obj",
        ".git",
        ".vs",
        ".vscode",
        ".idea",
        "Logs",
        "AutoGenerated",
        "oracle-data",
        "wwwroot",
        "artifacts",
        ".tmp",
        "node_modules"
    ];

    private static readonly Regex[] BlockedFilePatterns =
    [
        CreateRegex(
            @"^appsettings.*\.json$"),
        CreateRegex(
            @"^docker-compose.*\.yml$"),
        CreateRegex(
            @"^docker-compose.*\.yaml$"),
        CreateRegex(
            @".*\.key$"),
        CreateRegex(
            @".*\.pem$"),
        CreateRegex(
            @".*\.pfx$"),
        CreateRegex(
            @".*\.jks$"),
        CreateRegex(
            @".*\.keystore$")
    ];

    private static readonly Regex[] SecretPatterns =
    [
        CreateRegex(
            @"password\s*[:=]"),
        CreateRegex(
            @"passwd\s*[:=]"),
        CreateRegex(
            @"pwd\s*[:=]"),
        CreateRegex(
            @"secret\s*[:=]"),
        CreateRegex(
            @"token\s*[:=]"),
        CreateRegex(
            @"api[_-]?key\s*[:=]"),
        CreateRegex(
            @"connectionstring\s*[:=]")
    ];

    private static readonly JsonSerializerOptions JsonOptions =
        new()
        {
            WriteIndented = true
        };

    public SecretScanRunResult Run(
        string repoRoot)
    {
        if (string.IsNullOrWhiteSpace(
                repoRoot))
        {
            return SecretScanRunResult.Failure(
                "Repository root path cannot be empty.");
        }

        string root;

        try
        {
            root =
                Path.GetFullPath(
                    repoRoot);
        }
        catch (Exception exception)
        {
            return SecretScanRunResult.Failure(
                ProcessRunner.Redact(
                    exception.Message));
        }

        if (!Directory.Exists(root))
        {
            return SecretScanRunResult.Failure(
                "Repository root path was not found.");
        }

        try
        {
            List<SecretScanFinding> findings =
                [];

            IEnumerable<string> files =
                Directory
                    .EnumerateFiles(
                        root,
                        "*",
                        SearchOption.AllDirectories)
                    .OrderBy(
                        path =>
                            GetRelativePath(
                                root,
                                path),
                        StringComparer.Ordinal);

            foreach (string path in files)
            {
                string relativePath =
                    GetRelativePath(
                        root,
                        path);

                if (ShouldIgnorePath(
                        relativePath,
                        Path.GetFileName(path)))
                {
                    continue;
                }

                try
                {
                    FileInfo info =
                        new(path);

                    if (!info.Exists ||
                        info.Length >= MaxFileBytes)
                    {
                        continue;
                    }

                    foreach (string line in
                        File.ReadLines(path))
                    {
                        if (!SecretPatterns.Any(
                                pattern =>
                                    pattern.IsMatch(line)))
                        {
                            continue;
                        }

                        findings.Add(
                            new SecretScanFinding
                            {
                                File =
                                    relativePath
                            });
                    }
                }
                catch
                {
                    // Preserve historical behavior:
                    // unreadable individual files are skipped.
                }
            }

            SecretScanReport report =
                new()
                {
                    SecretsExposed = false,
                    SecretValuesReturned = false,
                    RedactedOnly = true,
                    FindingCount =
                        findings.Count,
                    Findings =
                        findings
                            .Take(
                                MaxReportedFindings)
                            .ToArray()
                };

            string reportPath =
                Path.Combine(
                    root,
                    ReportRelativePath.Replace(
                        '/',
                        Path.DirectorySeparatorChar));

            string? reportDirectory =
                Path.GetDirectoryName(
                    reportPath);

            if (!string.IsNullOrWhiteSpace(
                    reportDirectory))
            {
                Directory.CreateDirectory(
                    reportDirectory);
            }

            string json =
                JsonSerializer.Serialize(
                    report,
                    JsonOptions);

            File.WriteAllText(
                reportPath,
                json +
                Environment.NewLine);

            return SecretScanRunResult.Success(
                report);
        }
        catch (Exception exception)
        {
            return SecretScanRunResult.Failure(
                ProcessRunner.Redact(
                    exception.Message));
        }
    }

    private static bool ShouldIgnorePath(
        string relativePath,
        string fileName)
    {
        string normalized =
            relativePath.Replace(
                '\\',
                '/');

        foreach (string name in
            IgnoredDirectories)
        {
            if (string.Equals(
                    normalized,
                    name,
                    StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (normalized.StartsWith(
                    name + "/",
                    StringComparison.Ordinal))
            {
                return true;
            }

            if (normalized.Contains(
                    "/" + name + "/",
                    StringComparison.Ordinal))
            {
                return true;
            }
        }

        if (BlockedFilePatterns.Any(
                pattern =>
                    pattern.IsMatch(
                        fileName)))
        {
            return true;
        }

        if (normalized.StartsWith(
                ".build-",
                StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        string[] segments =
            normalized.Split(
                '/',
                StringSplitOptions.RemoveEmptyEntries);

        return segments.Any(
            segment =>
                string.Equals(
                    segment,
                    "migrations",
                    StringComparison.OrdinalIgnoreCase));
    }

    private static string GetRelativePath(
        string root,
        string fullPath)
    {
        return Path
            .GetRelativePath(
                root,
                fullPath)
            .Replace(
                '\\',
                '/');
    }

    private static Regex CreateRegex(
        string pattern)
    {
        return new Regex(
            pattern,
            RegexOptions.IgnoreCase |
            RegexOptions.CultureInvariant |
            RegexOptions.Compiled);
    }
}
