param(
    [string]$RepoRoot = ""
)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Resolve-Path (Join-Path $scriptRoot "..\..")).Path
}
else {
    $RepoRoot = (Resolve-Path $RepoRoot).Path
}
$ignored = @("bin","obj",".git",".vs",".vscode",".idea","Logs","AutoGenerated","oracle-data","wwwroot","artifacts",".tmp","node_modules")
$reportsRoot = Join-Path $RepoRoot ".ai/generated/reports"
$blockedNames = @("appsettings*.json","docker-compose*.yml","docker-compose*.yaml","*.key","*.pem","*.pfx","*.jks","*.keystore")
$patterns = @("password\s*[:=]","passwd\s*[:=]","pwd\s*[:=]","secret\s*[:=]","token\s*[:=]","api[_-]?key\s*[:=]","connectionstring\s*[:=]")

function Get-RelativePath([string]$Root, [string]$Path) {
    $rootFull = [IO.Path]::GetFullPath($Root).TrimEnd("\","/")
    $pathFull = [IO.Path]::GetFullPath($Path)
    if ($pathFull.StartsWith($rootFull, [StringComparison]::OrdinalIgnoreCase)) {
        return $pathFull.Substring($rootFull.Length).TrimStart("\","/")
    }
    return $pathFull
}

function Test-IgnoredPath([string]$Path) {
    $relative = (Get-RelativePath $RepoRoot $Path).Replace("\","/")
    foreach ($name in $ignored) {
        if ($relative -eq $name -or $relative.StartsWith("$name/") -or $relative.Contains("/$name/")) { return $true }
    }
    foreach ($name in $blockedNames) {
        if ((Split-Path $Path -Leaf) -like $name) { return $true }
    }
    return $relative -like ".build-*/*" -or $relative -like ".build-*" -or $relative -match "(^|/)migrations(/|$)"
}

$findings = New-Object System.Collections.ArrayList
Get-ChildItem -LiteralPath $RepoRoot -File -Recurse |
    Where-Object { -not (Test-IgnoredPath $_.FullName) -and $_.Length -lt 1048576 } |
    ForEach-Object {
        $relative = (Get-RelativePath $RepoRoot $_.FullName).Replace("\","/")
        try {
            foreach ($line in Get-Content -LiteralPath $_.FullName -ErrorAction Stop) {
                foreach ($pattern in $patterns) {
                    if ($line -match $pattern) {
                        $null = $findings.Add([pscustomobject]@{
                            file = $relative
                            category = "SecretPattern"
                            severity = "High"
                            preview = "<redacted>"
                        })
                        break
                    }
                }
            }
        }
        catch {
        }
    }

$report = [pscustomobject]@{
    SecretsExposed = $false
    SecretValuesReturned = $false
    RedactedOnly = $true
    FindingCount = $findings.Count
    Findings = @($findings | Select-Object -First 100)
}

New-Item -ItemType Directory -Path $reportsRoot -Force | Out-Null
$json = $report | ConvertTo-Json -Depth 5
$json | Set-Content -LiteralPath (Join-Path $reportsRoot "secret-scan-report.json") -Encoding UTF8
$json
