param(
    [string]$RepoRoot = ""
)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Resolve-Path (Join-Path $scriptRoot "..\..")).Path
}
else {
    $RepoRoot = (Resolve-Path $RepoRoot).Path
}

$ignored = @("bin","obj",".git",".vs",".vscode",".idea","Logs","AutoGenerated","oracle-data","wwwroot","artifacts",".tmp","node_modules")
$reportsRoot = Join-Path $RepoRoot ".ai/generated/reports"

function Get-RelativePath([string]$Root, [string]$Path) {
    $rootFull = [IO.Path]::GetFullPath($Root).TrimEnd("\","/")
    $pathFull = [IO.Path]::GetFullPath($Path)
    if ($pathFull.StartsWith($rootFull, [StringComparison]::OrdinalIgnoreCase)) {
        return $pathFull.Substring($rootFull.Length).TrimStart("\","/").Replace("\", "/")
    }
    return $pathFull.Replace("\", "/")
}

function Test-IgnoredPath([string]$Path) {
    $relative = (Get-RelativePath $RepoRoot $Path).Replace("\","/")
    foreach ($name in $ignored) {
        if ($relative -eq $name -or $relative.StartsWith("$name/") -or $relative.Contains("/$name/")) { return $true }
    }
    return $relative -like ".build-*/*" -or $relative -like ".build-*"
}

$sdk = dotnet --version
$sdks = dotnet --list-sdks
$projects = Get-ChildItem -LiteralPath $RepoRoot -Filter *.csproj -File -Recurse | Where-Object { -not (Test-IgnoredPath $_.FullName) }
$results = foreach ($project in $projects) {
    [xml]$xml = Get-Content -LiteralPath $project.FullName
    $tfms = @()
    $tfms += $xml.Project.PropertyGroup.TargetFramework
    $tfms += ($xml.Project.PropertyGroup.TargetFrameworks -split ";")
    [pscustomobject]@{
        Project = (Get-RelativePath $RepoRoot $project.FullName)
        TargetFrameworks = (@($tfms) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Sort-Object -Unique) -join ";"
    }
}

$report = [pscustomobject]@{
    ExpectedTargetFramework = "net10.0"
    DotNetSdkVersion = $sdk
    DotNetSdks = @($sdks)
    Projects = @($results)
}

New-Item -ItemType Directory -Path $reportsRoot -Force | Out-Null
$json = $report | ConvertTo-Json -Depth 6
$json | Set-Content -LiteralPath (Join-Path $reportsRoot "sdk-alignment-report.json") -Encoding UTF8
$json
