param(
    [string]$RepoRoot = "",
    [switch]$Apply
)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = (Resolve-Path (Join-Path $scriptRoot "..\..")).Path
}
else {
    $RepoRoot = (Resolve-Path $RepoRoot).Path
}

$ignored = @("bin","obj",".git",".vs",".vscode",".idea","Logs","AutoGenerated","oracle-data","wwwroot","artifacts",".tmp","node_modules")
$aiRoot = Join-Path $RepoRoot ".ai"
$manifestRoot = Join-Path $aiRoot "manifests"
$generatedRoot = Join-Path $aiRoot "generated"
$inventoriesRoot = Join-Path $generatedRoot "inventories"
$summariesRoot = Join-Path $generatedRoot "summaries"
$manifestPath = Join-Path $manifestRoot "mcp-context-manifest.json"

function Get-RelativePath([string]$Root, [string]$Path) {
    $rootFull = [IO.Path]::GetFullPath($Root).TrimEnd("\","/")
    $pathFull = [IO.Path]::GetFullPath($Path)
    if ($pathFull.StartsWith($rootFull, [StringComparison]::OrdinalIgnoreCase)) {
        return $pathFull.Substring($rootFull.Length).TrimStart("\","/").Replace("\", "/")
    }
    return $pathFull.Replace("\", "/")
}

function Test-IgnoredPath([string]$Path) {
    $relative = (Get-RelativePath $RepoRoot $Path).Replace("\","/")
    foreach ($name in $ignored) {
        if ($relative -eq $name -or $relative.StartsWith("$name/") -or $relative.Contains("/$name/")) { return $true }
    }
    return $relative -like ".build-*/*" -or $relative -like ".build-*"
}

function Redact([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) { return $Value }
    return ($Value -replace "(?i)(password|passwd|pwd|secret|token|apikey|api_key|connectionstring)\s*[:=]\s*[^;\s]+",'$1=<redacted>')
}

function Get-SafeRepoName([string]$Value) {
    $blockedFragments = @("Sandbox","Validation","PathBug","DoubleClick","ExeOnly")
    foreach ($fragment in $blockedFragments) {
        if ($Value.IndexOf($fragment, [StringComparison]::OrdinalIgnoreCase) -ge 0) { return "<target-repo>" }
    }
    if ($Value.IndexOf(("Sv" + "ala"), [StringComparison]::OrdinalIgnoreCase) -ge 0) { return "<target-repo>" }
    if ($Value.IndexOf(("Val" + "ter"), [StringComparison]::OrdinalIgnoreCase) -ge 0) { return "<target-repo>" }
    if ($Value.IndexOf(("neo" + "_" + "v"), [StringComparison]::OrdinalIgnoreCase) -ge 0) { return "<target-repo>" }
    return $Value
}

$solution = Get-ChildItem -LiteralPath $RepoRoot -Filter *.sln -File | Sort-Object Name | Select-Object -First 1
$projects = @(Get-ChildItem -LiteralPath $RepoRoot -Filter *.csproj -File -Recurse | Where-Object { -not (Test-IgnoredPath $_.FullName) } | Sort-Object FullName)
$projectItems = @($projects | ForEach-Object {
    [xml]$xml = Get-Content -LiteralPath $_.FullName
    $tfms = @()
    $tfms += $xml.Project.PropertyGroup.TargetFramework
    $tfms += ($xml.Project.PropertyGroup.TargetFrameworks -split ";")
    [ordered]@{
        path = (Get-RelativePath $RepoRoot $_.FullName)
        targetFrameworks = @($tfms | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Sort-Object -Unique)
    }
})
$references = @($projects | ForEach-Object {
    [xml]$xml = Get-Content -LiteralPath $_.FullName
    $projectPath = (Get-RelativePath $RepoRoot $_.FullName)
    foreach ($reference in @($xml.Project.ItemGroup.ProjectReference)) {
        if ($null -ne $reference.Include) {
            [ordered]@{
                project = $projectPath
                reference = ($reference.Include -replace "\\", "/")
            }
        }
    }
})
$packages = @($projects | ForEach-Object {
    [xml]$xml = Get-Content -LiteralPath $_.FullName
    $projectPath = (Get-RelativePath $RepoRoot $_.FullName)
    foreach ($package in @($xml.Project.ItemGroup.PackageReference)) {
        if ($null -ne $package.Include) {
            [ordered]@{
                project = $projectPath
                package = [string]$package.Include
                version = if ($null -ne $package.Version) { [string]$package.Version } else { "" }
            }
        }
    }
})
$sdkVersion = ""
$sdkList = @()
try { $sdkVersion = (dotnet --version) } catch { $sdkVersion = "Unavailable" }
try { $sdkList = @(dotnet --list-sdks) } catch { $sdkList = @("Unavailable") }

$summary = [ordered]@{
    repoName = Get-SafeRepoName (Split-Path $RepoRoot -Leaf)
    mainSolution = if ($solution) { $solution.Name } else { "" }
    generatedAtLocal = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")
    targetFramework = "net10.0"
    mcpServerName = "ai_repo_context"
    mcpProjectRelativePath = "Tools/AiContextMcp/AiRepo.ContextMcp.csproj"
    projectCount = @($projects).Count
    allowedContextFiles = @(
        ".ai/README.md",
        ".ai/ai-operating-rules.md",
        ".ai/automation-risks.md",
        ".ai/build-profile.md",
        ".ai/codex-usage-guide.md",
        ".ai/project-map.md",
        ".ai/sdk-profile.md",
        ".ai/test-profile.md",
        ".ai/tool-roadmap.md",
        ".ai/context-budget.json",
        ".ai/generated/inventories/project-inventory.json",
        ".ai/generated/inventories/project-references.json",
        ".ai/generated/inventories/package-inventory.json",
        ".ai/generated/inventories/sdk-inventory.json",
        ".ai/generated/inventories/symbol-inventory.json",
        ".ai/generated/inventories/symbol-inventory.md",
        ".ai/generated/inventories/endpoint-inventory.json",
        ".ai/generated/inventories/endpoint-inventory.md",
        ".ai/generated/reports/mcp-budget-report.json",
        ".ai/generated/reports/mcp-budget-report.md",
        ".ai/generated/reports/sdk-alignment-report.json",
        ".ai/generated/reports/secret-scan-report.json",
        ".ai/generated/reports/build-diagnostics-report.json",
        ".ai/generated/reports/latest-build-summary.json",
        ".ai/generated/summaries/generated-context-summary.md",
        ".ai/manifests/mcp-context-manifest.md",
        ".ai/playbooks/change-ui.md",
        ".ai/playbooks/diagnose-build.md",
        ".ai/playbooks/update-package.md",
        ".ai/playbooks/inspect-security.md"
    )
    restrictedPaths = @(
        ".git",
        ".vs",
        ".vscode",
        ".idea",
        "bin",
        "obj",
        "artifacts",
        ".tmp",
        ".dotnet-home",
        ".codex/config.toml",
        "Logs",
        "AutoGenerated",
        "oracle-data",
        "wwwroot",
        ".build-*",
        "appsettings*.json",
        "docker-compose*.yml",
        "docker-compose*.yaml",
        "*.key",
        "*.pem",
        "*.pfx",
        "*.jks",
        "*.keystore",
        "migrations"
    )
    budgets = [ordered]@{
        compactBytes = 8192
        fullBytes = 49152
        combinedBytes = 65536
        fileReadBytes = 1048576
        searchDefaultLimit = 5
        searchHardLimit = 25
        arrayDefaultLimit = 25
        arrayHardLimit = 100
        previewChars = 240
    }
}

New-Item -ItemType Directory -Path $manifestRoot -Force | Out-Null
New-Item -ItemType Directory -Path $inventoriesRoot -Force | Out-Null
New-Item -ItemType Directory -Path $summariesRoot -Force | Out-Null
($summary | ConvertTo-Json -Depth 8) | Set-Content -LiteralPath $manifestPath -Encoding UTF8
([ordered]@{ generatedAtLocal = $summary.generatedAtLocal; projects = @($projectItems) } | ConvertTo-Json -Depth 8) | Set-Content -LiteralPath (Join-Path $inventoriesRoot "project-inventory.json") -Encoding UTF8
([ordered]@{ generatedAtLocal = $summary.generatedAtLocal; references = @($references) } | ConvertTo-Json -Depth 8) | Set-Content -LiteralPath (Join-Path $inventoriesRoot "project-references.json") -Encoding UTF8
([ordered]@{ generatedAtLocal = $summary.generatedAtLocal; packages = @($packages) } | ConvertTo-Json -Depth 8) | Set-Content -LiteralPath (Join-Path $inventoriesRoot "package-inventory.json") -Encoding UTF8
([ordered]@{ generatedAtLocal = $summary.generatedAtLocal; dotNetSdkVersion = $sdkVersion; dotNetSdks = @($sdkList); expectedTargetFramework = "net10.0" } | ConvertTo-Json -Depth 8) | Set-Content -LiteralPath (Join-Path $inventoriesRoot "sdk-inventory.json") -Encoding UTF8
$summaryMarkdown = @(
    "# Generated Context Summary",
    "",
    "- Generated: $($summary.generatedAtLocal)",
    "- Main solution: $($summary.mainSolution)",
    "- Projects: $($summary.projectCount)",
    "- Packages: $(@($packages).Count)",
    "- Project references: $(@($references).Count)"
)
$summaryMarkdown | Set-Content -LiteralPath (Join-Path $summariesRoot "generated-context-summary.md") -Encoding UTF8
Write-Output (Redact "Updated .ai/generated/ context inventories and summaries.")
